#
# Copyright 2020 Alexander Vollschwitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-maker
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - list
  - get
  - create
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - list
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-maker
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: label-maker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-maker
subjects:
- kind: ServiceAccount
  name: label-maker
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-label-maker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: label-maker
  template:
    metadata:
      labels:
        name: label-maker
    spec:
      serviceAccountName: label-maker
      containers:
        - name: label-maker
          image: xelalex/label-maker
          command:
          - label-maker
          imagePullPolicy: Always
          env:
            - name: ROLE_LABEL
              value: "node.kubernetes.io/role"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "label-maker"
